/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * StudyCore API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ActivityItem,
  BranchTree,
  CreateBranchTreeBody,
  CreateFlashcardBody,
  CreateFlashcardDeckBody,
  CreateGlossaryTermBody,
  CreateNoteBody,
  CreateStudySetBody,
  DefineTermBody,
  ErrorEnvelope,
  Flashcard,
  FlashcardDeck,
  FlashcardDeckDetail,
  GenerateBranchTreeBody,
  GenerateFlashcardsBody,
  GlobalSearchParams,
  GlossaryTerm,
  HealthStatus,
  ListFlashcardDecksParams,
  ListGlossaryTermsParams,
  ListNotesParams,
  ListSetsParams,
  Note,
  OverviewStats,
  SearchResults,
  StudySet,
  SummarizeNoteBody,
  SummaryResult,
  UpdateNoteBody,
  UploadUrlRequest,
  UploadUrlResponse,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all notes
 */
export const getListNotesUrl = (params?: ListNotesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/notes?${stringifiedParams}`
    : `/api/notes`;
};

export const listNotes = async (
  params?: ListNotesParams,
  options?: RequestInit,
): Promise<Note[]> => {
  return customFetch<Note[]>(getListNotesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListNotesQueryKey = (params?: ListNotesParams) => {
  return [`/api/notes`, ...(params ? [params] : [])] as const;
};

export const getListNotesQueryOptions = <
  TData = Awaited<ReturnType<typeof listNotes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListNotesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listNotes>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListNotesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotes>>> = ({
    signal,
  }) => listNotes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listNotes>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListNotesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listNotes>>
>;
export type ListNotesQueryError = ErrorType<unknown>;

/**
 * @summary List all notes
 */

export function useListNotes<
  TData = Awaited<ReturnType<typeof listNotes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListNotesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listNotes>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListNotesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new note
 */
export const getCreateNoteUrl = () => {
  return `/api/notes`;
};

export const createNote = async (
  createNoteBody: CreateNoteBody,
  options?: RequestInit,
): Promise<Note> => {
  return customFetch<Note>(getCreateNoteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createNoteBody),
  });
};

export const getCreateNoteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNote>>,
    TError,
    { data: BodyType<CreateNoteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createNote>>,
  TError,
  { data: BodyType<CreateNoteBody> },
  TContext
> => {
  const mutationKey = ["createNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createNote>>,
    { data: BodyType<CreateNoteBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createNote(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof createNote>>
>;
export type CreateNoteMutationBody = BodyType<CreateNoteBody>;
export type CreateNoteMutationError = ErrorType<unknown>;

/**
 * @summary Create a new note
 */
export const useCreateNote = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNote>>,
    TError,
    { data: BodyType<CreateNoteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createNote>>,
  TError,
  { data: BodyType<CreateNoteBody> },
  TContext
> => {
  return useMutation(getCreateNoteMutationOptions(options));
};

export const getGetNoteUrl = (id: string) => {
  return `/api/notes/${id}`;
};

export const getNote = async (
  id: string,
  options?: RequestInit,
): Promise<Note> => {
  return customFetch<Note>(getGetNoteUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetNoteQueryKey = (id: string) => {
  return [`/api/notes/${id}`] as const;
};

export const getGetNoteQueryOptions = <
  TData = Awaited<ReturnType<typeof getNote>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNote>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNoteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNote>>> = ({
    signal,
  }) => getNote(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getNote>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetNoteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNote>>
>;
export type GetNoteQueryError = ErrorType<unknown>;

export function useGetNote<
  TData = Awaited<ReturnType<typeof getNote>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNote>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNoteQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getUpdateNoteUrl = (id: string) => {
  return `/api/notes/${id}`;
};

export const updateNote = async (
  id: string,
  updateNoteBody: UpdateNoteBody,
  options?: RequestInit,
): Promise<Note> => {
  return customFetch<Note>(getUpdateNoteUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateNoteBody),
  });
};

export const getUpdateNoteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNote>>,
    TError,
    { id: string; data: BodyType<UpdateNoteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateNote>>,
  TError,
  { id: string; data: BodyType<UpdateNoteBody> },
  TContext
> => {
  const mutationKey = ["updateNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateNote>>,
    { id: string; data: BodyType<UpdateNoteBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateNote(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateNote>>
>;
export type UpdateNoteMutationBody = BodyType<UpdateNoteBody>;
export type UpdateNoteMutationError = ErrorType<unknown>;

export const useUpdateNote = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNote>>,
    TError,
    { id: string; data: BodyType<UpdateNoteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateNote>>,
  TError,
  { id: string; data: BodyType<UpdateNoteBody> },
  TContext
> => {
  return useMutation(getUpdateNoteMutationOptions(options));
};

export const getDeleteNoteUrl = (id: string) => {
  return `/api/notes/${id}`;
};

export const deleteNote = async (
  id: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteNoteUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteNoteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNote>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteNote>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteNote>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteNote(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteNote>>
>;

export type DeleteNoteMutationError = ErrorType<unknown>;

export const useDeleteNote = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNote>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteNote>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteNoteMutationOptions(options));
};

/**
 * @summary List all flashcard decks
 */
export const getListFlashcardDecksUrl = (params?: ListFlashcardDecksParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/flashcard-decks?${stringifiedParams}`
    : `/api/flashcard-decks`;
};

export const listFlashcardDecks = async (
  params?: ListFlashcardDecksParams,
  options?: RequestInit,
): Promise<FlashcardDeck[]> => {
  return customFetch<FlashcardDeck[]>(getListFlashcardDecksUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListFlashcardDecksQueryKey = (
  params?: ListFlashcardDecksParams,
) => {
  return [`/api/flashcard-decks`, ...(params ? [params] : [])] as const;
};

export const getListFlashcardDecksQueryOptions = <
  TData = Awaited<ReturnType<typeof listFlashcardDecks>>,
  TError = ErrorType<unknown>,
>(
  params?: ListFlashcardDecksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listFlashcardDecks>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListFlashcardDecksQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listFlashcardDecks>>
  > = ({ signal }) => listFlashcardDecks(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listFlashcardDecks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListFlashcardDecksQueryResult = NonNullable<
  Awaited<ReturnType<typeof listFlashcardDecks>>
>;
export type ListFlashcardDecksQueryError = ErrorType<unknown>;

/**
 * @summary List all flashcard decks
 */

export function useListFlashcardDecks<
  TData = Awaited<ReturnType<typeof listFlashcardDecks>>,
  TError = ErrorType<unknown>,
>(
  params?: ListFlashcardDecksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listFlashcardDecks>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListFlashcardDecksQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a flashcard deck
 */
export const getCreateFlashcardDeckUrl = () => {
  return `/api/flashcard-decks`;
};

export const createFlashcardDeck = async (
  createFlashcardDeckBody: CreateFlashcardDeckBody,
  options?: RequestInit,
): Promise<FlashcardDeck> => {
  return customFetch<FlashcardDeck>(getCreateFlashcardDeckUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createFlashcardDeckBody),
  });
};

export const getCreateFlashcardDeckMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFlashcardDeck>>,
    TError,
    { data: BodyType<CreateFlashcardDeckBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createFlashcardDeck>>,
  TError,
  { data: BodyType<CreateFlashcardDeckBody> },
  TContext
> => {
  const mutationKey = ["createFlashcardDeck"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createFlashcardDeck>>,
    { data: BodyType<CreateFlashcardDeckBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createFlashcardDeck(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateFlashcardDeckMutationResult = NonNullable<
  Awaited<ReturnType<typeof createFlashcardDeck>>
>;
export type CreateFlashcardDeckMutationBody = BodyType<CreateFlashcardDeckBody>;
export type CreateFlashcardDeckMutationError = ErrorType<unknown>;

/**
 * @summary Create a flashcard deck
 */
export const useCreateFlashcardDeck = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFlashcardDeck>>,
    TError,
    { data: BodyType<CreateFlashcardDeckBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createFlashcardDeck>>,
  TError,
  { data: BodyType<CreateFlashcardDeckBody> },
  TContext
> => {
  return useMutation(getCreateFlashcardDeckMutationOptions(options));
};

export const getGetFlashcardDeckUrl = (id: string) => {
  return `/api/flashcard-decks/${id}`;
};

export const getFlashcardDeck = async (
  id: string,
  options?: RequestInit,
): Promise<FlashcardDeckDetail> => {
  return customFetch<FlashcardDeckDetail>(getGetFlashcardDeckUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetFlashcardDeckQueryKey = (id: string) => {
  return [`/api/flashcard-decks/${id}`] as const;
};

export const getGetFlashcardDeckQueryOptions = <
  TData = Awaited<ReturnType<typeof getFlashcardDeck>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFlashcardDeck>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFlashcardDeckQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFlashcardDeck>>
  > = ({ signal }) => getFlashcardDeck(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFlashcardDeck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFlashcardDeckQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFlashcardDeck>>
>;
export type GetFlashcardDeckQueryError = ErrorType<unknown>;

export function useGetFlashcardDeck<
  TData = Awaited<ReturnType<typeof getFlashcardDeck>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFlashcardDeck>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFlashcardDeckQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getDeleteFlashcardDeckUrl = (id: string) => {
  return `/api/flashcard-decks/${id}`;
};

export const deleteFlashcardDeck = async (
  id: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteFlashcardDeckUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteFlashcardDeckMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteFlashcardDeck>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteFlashcardDeck>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteFlashcardDeck"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteFlashcardDeck>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteFlashcardDeck(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteFlashcardDeckMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteFlashcardDeck>>
>;

export type DeleteFlashcardDeckMutationError = ErrorType<unknown>;

export const useDeleteFlashcardDeck = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteFlashcardDeck>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteFlashcardDeck>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteFlashcardDeckMutationOptions(options));
};

export const getListFlashcardsUrl = (id: string) => {
  return `/api/flashcard-decks/${id}/cards`;
};

export const listFlashcards = async (
  id: string,
  options?: RequestInit,
): Promise<Flashcard[]> => {
  return customFetch<Flashcard[]>(getListFlashcardsUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getListFlashcardsQueryKey = (id: string) => {
  return [`/api/flashcard-decks/${id}/cards`] as const;
};

export const getListFlashcardsQueryOptions = <
  TData = Awaited<ReturnType<typeof listFlashcards>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listFlashcards>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListFlashcardsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlashcards>>> = ({
    signal,
  }) => listFlashcards(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listFlashcards>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListFlashcardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listFlashcards>>
>;
export type ListFlashcardsQueryError = ErrorType<unknown>;

export function useListFlashcards<
  TData = Awaited<ReturnType<typeof listFlashcards>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listFlashcards>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListFlashcardsQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getAddFlashcardUrl = (id: string) => {
  return `/api/flashcard-decks/${id}/cards`;
};

export const addFlashcard = async (
  id: string,
  createFlashcardBody: CreateFlashcardBody,
  options?: RequestInit,
): Promise<Flashcard> => {
  return customFetch<Flashcard>(getAddFlashcardUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createFlashcardBody),
  });
};

export const getAddFlashcardMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addFlashcard>>,
    TError,
    { id: string; data: BodyType<CreateFlashcardBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addFlashcard>>,
  TError,
  { id: string; data: BodyType<CreateFlashcardBody> },
  TContext
> => {
  const mutationKey = ["addFlashcard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addFlashcard>>,
    { id: string; data: BodyType<CreateFlashcardBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return addFlashcard(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddFlashcardMutationResult = NonNullable<
  Awaited<ReturnType<typeof addFlashcard>>
>;
export type AddFlashcardMutationBody = BodyType<CreateFlashcardBody>;
export type AddFlashcardMutationError = ErrorType<unknown>;

export const useAddFlashcard = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addFlashcard>>,
    TError,
    { id: string; data: BodyType<CreateFlashcardBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addFlashcard>>,
  TError,
  { id: string; data: BodyType<CreateFlashcardBody> },
  TContext
> => {
  return useMutation(getAddFlashcardMutationOptions(options));
};

export const getListGlossaryTermsUrl = (params?: ListGlossaryTermsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/glossary?${stringifiedParams}`
    : `/api/glossary`;
};

export const listGlossaryTerms = async (
  params?: ListGlossaryTermsParams,
  options?: RequestInit,
): Promise<GlossaryTerm[]> => {
  return customFetch<GlossaryTerm[]>(getListGlossaryTermsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListGlossaryTermsQueryKey = (
  params?: ListGlossaryTermsParams,
) => {
  return [`/api/glossary`, ...(params ? [params] : [])] as const;
};

export const getListGlossaryTermsQueryOptions = <
  TData = Awaited<ReturnType<typeof listGlossaryTerms>>,
  TError = ErrorType<unknown>,
>(
  params?: ListGlossaryTermsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listGlossaryTerms>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListGlossaryTermsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listGlossaryTerms>>
  > = ({ signal }) => listGlossaryTerms(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listGlossaryTerms>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListGlossaryTermsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listGlossaryTerms>>
>;
export type ListGlossaryTermsQueryError = ErrorType<unknown>;

export function useListGlossaryTerms<
  TData = Awaited<ReturnType<typeof listGlossaryTerms>>,
  TError = ErrorType<unknown>,
>(
  params?: ListGlossaryTermsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listGlossaryTerms>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListGlossaryTermsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getCreateGlossaryTermUrl = () => {
  return `/api/glossary`;
};

export const createGlossaryTerm = async (
  createGlossaryTermBody: CreateGlossaryTermBody,
  options?: RequestInit,
): Promise<GlossaryTerm> => {
  return customFetch<GlossaryTerm>(getCreateGlossaryTermUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createGlossaryTermBody),
  });
};

export const getCreateGlossaryTermMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createGlossaryTerm>>,
    TError,
    { data: BodyType<CreateGlossaryTermBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createGlossaryTerm>>,
  TError,
  { data: BodyType<CreateGlossaryTermBody> },
  TContext
> => {
  const mutationKey = ["createGlossaryTerm"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createGlossaryTerm>>,
    { data: BodyType<CreateGlossaryTermBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createGlossaryTerm(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateGlossaryTermMutationResult = NonNullable<
  Awaited<ReturnType<typeof createGlossaryTerm>>
>;
export type CreateGlossaryTermMutationBody = BodyType<CreateGlossaryTermBody>;
export type CreateGlossaryTermMutationError = ErrorType<unknown>;

export const useCreateGlossaryTerm = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createGlossaryTerm>>,
    TError,
    { data: BodyType<CreateGlossaryTermBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createGlossaryTerm>>,
  TError,
  { data: BodyType<CreateGlossaryTermBody> },
  TContext
> => {
  return useMutation(getCreateGlossaryTermMutationOptions(options));
};

export const getUpdateGlossaryTermUrl = (id: string) => {
  return `/api/glossary/${id}`;
};

export const updateGlossaryTerm = async (
  id: string,
  createGlossaryTermBody: CreateGlossaryTermBody,
  options?: RequestInit,
): Promise<GlossaryTerm> => {
  return customFetch<GlossaryTerm>(getUpdateGlossaryTermUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createGlossaryTermBody),
  });
};

export const getUpdateGlossaryTermMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGlossaryTerm>>,
    TError,
    { id: string; data: BodyType<CreateGlossaryTermBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateGlossaryTerm>>,
  TError,
  { id: string; data: BodyType<CreateGlossaryTermBody> },
  TContext
> => {
  const mutationKey = ["updateGlossaryTerm"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateGlossaryTerm>>,
    { id: string; data: BodyType<CreateGlossaryTermBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateGlossaryTerm(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateGlossaryTermMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateGlossaryTerm>>
>;
export type UpdateGlossaryTermMutationBody = BodyType<CreateGlossaryTermBody>;
export type UpdateGlossaryTermMutationError = ErrorType<unknown>;

export const useUpdateGlossaryTerm = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGlossaryTerm>>,
    TError,
    { id: string; data: BodyType<CreateGlossaryTermBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateGlossaryTerm>>,
  TError,
  { id: string; data: BodyType<CreateGlossaryTermBody> },
  TContext
> => {
  return useMutation(getUpdateGlossaryTermMutationOptions(options));
};

export const getDeleteGlossaryTermUrl = (id: string) => {
  return `/api/glossary/${id}`;
};

export const deleteGlossaryTerm = async (
  id: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteGlossaryTermUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteGlossaryTermMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGlossaryTerm>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteGlossaryTerm>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteGlossaryTerm"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteGlossaryTerm>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteGlossaryTerm(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteGlossaryTermMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteGlossaryTerm>>
>;

export type DeleteGlossaryTermMutationError = ErrorType<unknown>;

export const useDeleteGlossaryTerm = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGlossaryTerm>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteGlossaryTerm>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteGlossaryTermMutationOptions(options));
};

export const getListBranchTreesUrl = () => {
  return `/api/branch-trees`;
};

export const listBranchTrees = async (
  options?: RequestInit,
): Promise<BranchTree[]> => {
  return customFetch<BranchTree[]>(getListBranchTreesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListBranchTreesQueryKey = () => {
  return [`/api/branch-trees`] as const;
};

export const getListBranchTreesQueryOptions = <
  TData = Awaited<ReturnType<typeof listBranchTrees>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listBranchTrees>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListBranchTreesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listBranchTrees>>> = ({
    signal,
  }) => listBranchTrees({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listBranchTrees>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListBranchTreesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listBranchTrees>>
>;
export type ListBranchTreesQueryError = ErrorType<unknown>;

export function useListBranchTrees<
  TData = Awaited<ReturnType<typeof listBranchTrees>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listBranchTrees>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListBranchTreesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getCreateBranchTreeUrl = () => {
  return `/api/branch-trees`;
};

export const createBranchTree = async (
  createBranchTreeBody: CreateBranchTreeBody,
  options?: RequestInit,
): Promise<BranchTree> => {
  return customFetch<BranchTree>(getCreateBranchTreeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createBranchTreeBody),
  });
};

export const getCreateBranchTreeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBranchTree>>,
    TError,
    { data: BodyType<CreateBranchTreeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBranchTree>>,
  TError,
  { data: BodyType<CreateBranchTreeBody> },
  TContext
> => {
  const mutationKey = ["createBranchTree"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBranchTree>>,
    { data: BodyType<CreateBranchTreeBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createBranchTree(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBranchTreeMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBranchTree>>
>;
export type CreateBranchTreeMutationBody = BodyType<CreateBranchTreeBody>;
export type CreateBranchTreeMutationError = ErrorType<unknown>;

export const useCreateBranchTree = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBranchTree>>,
    TError,
    { data: BodyType<CreateBranchTreeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createBranchTree>>,
  TError,
  { data: BodyType<CreateBranchTreeBody> },
  TContext
> => {
  return useMutation(getCreateBranchTreeMutationOptions(options));
};

export const getGetBranchTreeUrl = (id: string) => {
  return `/api/branch-trees/${id}`;
};

export const getBranchTree = async (
  id: string,
  options?: RequestInit,
): Promise<BranchTree> => {
  return customFetch<BranchTree>(getGetBranchTreeUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetBranchTreeQueryKey = (id: string) => {
  return [`/api/branch-trees/${id}`] as const;
};

export const getGetBranchTreeQueryOptions = <
  TData = Awaited<ReturnType<typeof getBranchTree>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBranchTree>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBranchTreeQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBranchTree>>> = ({
    signal,
  }) => getBranchTree(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBranchTree>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBranchTreeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBranchTree>>
>;
export type GetBranchTreeQueryError = ErrorType<unknown>;

export function useGetBranchTree<
  TData = Awaited<ReturnType<typeof getBranchTree>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBranchTree>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBranchTreeQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getDeleteBranchTreeUrl = (id: string) => {
  return `/api/branch-trees/${id}`;
};

export const deleteBranchTree = async (
  id: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteBranchTreeUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteBranchTreeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBranchTree>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBranchTree>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteBranchTree"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBranchTree>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBranchTree(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBranchTreeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBranchTree>>
>;

export type DeleteBranchTreeMutationError = ErrorType<unknown>;

export const useDeleteBranchTree = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBranchTree>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteBranchTree>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteBranchTreeMutationOptions(options));
};

export const getListSetsUrl = (params?: ListSetsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/sets?${stringifiedParams}`
    : `/api/sets`;
};

export const listSets = async (
  params?: ListSetsParams,
  options?: RequestInit,
): Promise<StudySet[]> => {
  return customFetch<StudySet[]>(getListSetsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListSetsQueryKey = (params?: ListSetsParams) => {
  return [`/api/sets`, ...(params ? [params] : [])] as const;
};

export const getListSetsQueryOptions = <
  TData = Awaited<ReturnType<typeof listSets>>,
  TError = ErrorType<unknown>,
>(
  params?: ListSetsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listSets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListSetsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listSets>>> = ({
    signal,
  }) => listSets(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSets>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListSetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSets>>
>;
export type ListSetsQueryError = ErrorType<unknown>;

export function useListSets<
  TData = Awaited<ReturnType<typeof listSets>>,
  TError = ErrorType<unknown>,
>(
  params?: ListSetsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listSets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListSetsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getCreateSetUrl = () => {
  return `/api/sets`;
};

export const createSet = async (
  createStudySetBody: CreateStudySetBody,
  options?: RequestInit,
): Promise<StudySet> => {
  return customFetch<StudySet>(getCreateSetUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createStudySetBody),
  });
};

export const getCreateSetMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSet>>,
    TError,
    { data: BodyType<CreateStudySetBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSet>>,
  TError,
  { data: BodyType<CreateStudySetBody> },
  TContext
> => {
  const mutationKey = ["createSet"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSet>>,
    { data: BodyType<CreateStudySetBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createSet(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSetMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSet>>
>;
export type CreateSetMutationBody = BodyType<CreateStudySetBody>;
export type CreateSetMutationError = ErrorType<unknown>;

export const useCreateSet = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSet>>,
    TError,
    { data: BodyType<CreateStudySetBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createSet>>,
  TError,
  { data: BodyType<CreateStudySetBody> },
  TContext
> => {
  return useMutation(getCreateSetMutationOptions(options));
};

export const getGetSetUrl = (id: string) => {
  return `/api/sets/${id}`;
};

export const getSet = async (
  id: string,
  options?: RequestInit,
): Promise<StudySet> => {
  return customFetch<StudySet>(getGetSetUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetSetQueryKey = (id: string) => {
  return [`/api/sets/${id}`] as const;
};

export const getGetSetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSet>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSet>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSetQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSet>>> = ({
    signal,
  }) => getSet(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getSet>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetSetQueryResult = NonNullable<Awaited<ReturnType<typeof getSet>>>;
export type GetSetQueryError = ErrorType<unknown>;

export function useGetSet<
  TData = Awaited<ReturnType<typeof getSet>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSet>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSetQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getDeleteSetUrl = (id: string) => {
  return `/api/sets/${id}`;
};

export const deleteSet = async (
  id: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteSetUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteSetMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSet>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSet>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteSet"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSet>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteSet(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSetMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSet>>
>;

export type DeleteSetMutationError = ErrorType<unknown>;

export const useDeleteSet = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSet>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteSet>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteSetMutationOptions(options));
};

/**
 * @summary Search across notes, flashcards, glossary, and sets
 */
export const getGlobalSearchUrl = (params: GlobalSearchParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/search?${stringifiedParams}`
    : `/api/search`;
};

export const globalSearch = async (
  params: GlobalSearchParams,
  options?: RequestInit,
): Promise<SearchResults> => {
  return customFetch<SearchResults>(getGlobalSearchUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGlobalSearchQueryKey = (params?: GlobalSearchParams) => {
  return [`/api/search`, ...(params ? [params] : [])] as const;
};

export const getGlobalSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof globalSearch>>,
  TError = ErrorType<unknown>,
>(
  params: GlobalSearchParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof globalSearch>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGlobalSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof globalSearch>>> = ({
    signal,
  }) => globalSearch(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof globalSearch>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GlobalSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof globalSearch>>
>;
export type GlobalSearchQueryError = ErrorType<unknown>;

/**
 * @summary Search across notes, flashcards, glossary, and sets
 */

export function useGlobalSearch<
  TData = Awaited<ReturnType<typeof globalSearch>>,
  TError = ErrorType<unknown>,
>(
  params: GlobalSearchParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof globalSearch>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGlobalSearchQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Dashboard overview stats
 */
export const getGetOverviewStatsUrl = () => {
  return `/api/stats/overview`;
};

export const getOverviewStats = async (
  options?: RequestInit,
): Promise<OverviewStats> => {
  return customFetch<OverviewStats>(getGetOverviewStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetOverviewStatsQueryKey = () => {
  return [`/api/stats/overview`] as const;
};

export const getGetOverviewStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOverviewStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewStats>>
  > = ({ signal }) => getOverviewStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOverviewStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewStats>>
>;
export type GetOverviewStatsQueryError = ErrorType<unknown>;

/**
 * @summary Dashboard overview stats
 */

export function useGetOverviewStats<
  TData = Awaited<ReturnType<typeof getOverviewStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOverviewStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Recent activity feed
 */
export const getGetRecentActivityUrl = () => {
  return `/api/stats/recent`;
};

export const getRecentActivity = async (
  options?: RequestInit,
): Promise<ActivityItem[]> => {
  return customFetch<ActivityItem[]>(getGetRecentActivityUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetRecentActivityQueryKey = () => {
  return [`/api/stats/recent`] as const;
};

export const getGetRecentActivityQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecentActivity>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRecentActivity>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecentActivityQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentActivity>>
  > = ({ signal }) => getRecentActivity({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentActivity>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRecentActivityQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentActivity>>
>;
export type GetRecentActivityQueryError = ErrorType<unknown>;

/**
 * @summary Recent activity feed
 */

export function useGetRecentActivity<
  TData = Awaited<ReturnType<typeof getRecentActivity>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRecentActivity>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRecentActivityQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary AI-generate flashcards from note content
 */
export const getGenerateFlashcardsUrl = () => {
  return `/api/ai/generate-flashcards`;
};

export const generateFlashcards = async (
  generateFlashcardsBody: GenerateFlashcardsBody,
  options?: RequestInit,
): Promise<FlashcardDeckDetail> => {
  return customFetch<FlashcardDeckDetail>(getGenerateFlashcardsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(generateFlashcardsBody),
  });
};

export const getGenerateFlashcardsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateFlashcards>>,
    TError,
    { data: BodyType<GenerateFlashcardsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateFlashcards>>,
  TError,
  { data: BodyType<GenerateFlashcardsBody> },
  TContext
> => {
  const mutationKey = ["generateFlashcards"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateFlashcards>>,
    { data: BodyType<GenerateFlashcardsBody> }
  > = (props) => {
    const { data } = props ?? {};

    return generateFlashcards(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateFlashcardsMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateFlashcards>>
>;
export type GenerateFlashcardsMutationBody = BodyType<GenerateFlashcardsBody>;
export type GenerateFlashcardsMutationError = ErrorType<unknown>;

/**
 * @summary AI-generate flashcards from note content
 */
export const useGenerateFlashcards = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateFlashcards>>,
    TError,
    { data: BodyType<GenerateFlashcardsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof generateFlashcards>>,
  TError,
  { data: BodyType<GenerateFlashcardsBody> },
  TContext
> => {
  return useMutation(getGenerateFlashcardsMutationOptions(options));
};

/**
 * @summary AI-generate a branch/mind-map tree from note content
 */
export const getGenerateBranchTreeUrl = () => {
  return `/api/ai/generate-branch-tree`;
};

export const generateBranchTree = async (
  generateBranchTreeBody: GenerateBranchTreeBody,
  options?: RequestInit,
): Promise<BranchTree> => {
  return customFetch<BranchTree>(getGenerateBranchTreeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(generateBranchTreeBody),
  });
};

export const getGenerateBranchTreeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateBranchTree>>,
    TError,
    { data: BodyType<GenerateBranchTreeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateBranchTree>>,
  TError,
  { data: BodyType<GenerateBranchTreeBody> },
  TContext
> => {
  const mutationKey = ["generateBranchTree"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateBranchTree>>,
    { data: BodyType<GenerateBranchTreeBody> }
  > = (props) => {
    const { data } = props ?? {};

    return generateBranchTree(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateBranchTreeMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateBranchTree>>
>;
export type GenerateBranchTreeMutationBody = BodyType<GenerateBranchTreeBody>;
export type GenerateBranchTreeMutationError = ErrorType<unknown>;

/**
 * @summary AI-generate a branch/mind-map tree from note content
 */
export const useGenerateBranchTree = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateBranchTree>>,
    TError,
    { data: BodyType<GenerateBranchTreeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof generateBranchTree>>,
  TError,
  { data: BodyType<GenerateBranchTreeBody> },
  TContext
> => {
  return useMutation(getGenerateBranchTreeMutationOptions(options));
};

/**
 * @summary AI-define a glossary term
 */
export const getDefineTermUrl = () => {
  return `/api/ai/define-term`;
};

export const defineTerm = async (
  defineTermBody: DefineTermBody,
  options?: RequestInit,
): Promise<GlossaryTerm> => {
  return customFetch<GlossaryTerm>(getDefineTermUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(defineTermBody),
  });
};

export const getDefineTermMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof defineTerm>>,
    TError,
    { data: BodyType<DefineTermBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof defineTerm>>,
  TError,
  { data: BodyType<DefineTermBody> },
  TContext
> => {
  const mutationKey = ["defineTerm"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof defineTerm>>,
    { data: BodyType<DefineTermBody> }
  > = (props) => {
    const { data } = props ?? {};

    return defineTerm(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DefineTermMutationResult = NonNullable<
  Awaited<ReturnType<typeof defineTerm>>
>;
export type DefineTermMutationBody = BodyType<DefineTermBody>;
export type DefineTermMutationError = ErrorType<unknown>;

/**
 * @summary AI-define a glossary term
 */
export const useDefineTerm = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof defineTerm>>,
    TError,
    { data: BodyType<DefineTermBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof defineTerm>>,
  TError,
  { data: BodyType<DefineTermBody> },
  TContext
> => {
  return useMutation(getDefineTermMutationOptions(options));
};

/**
 * @summary AI-summarize note into bullet points
 */
export const getSummarizeNoteUrl = () => {
  return `/api/ai/summarize`;
};

export const summarizeNote = async (
  summarizeNoteBody: SummarizeNoteBody,
  options?: RequestInit,
): Promise<SummaryResult> => {
  return customFetch<SummaryResult>(getSummarizeNoteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(summarizeNoteBody),
  });
};

export const getSummarizeNoteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof summarizeNote>>,
    TError,
    { data: BodyType<SummarizeNoteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof summarizeNote>>,
  TError,
  { data: BodyType<SummarizeNoteBody> },
  TContext
> => {
  const mutationKey = ["summarizeNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof summarizeNote>>,
    { data: BodyType<SummarizeNoteBody> }
  > = (props) => {
    const { data } = props ?? {};

    return summarizeNote(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SummarizeNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof summarizeNote>>
>;
export type SummarizeNoteMutationBody = BodyType<SummarizeNoteBody>;
export type SummarizeNoteMutationError = ErrorType<unknown>;

/**
 * @summary AI-summarize note into bullet points
 */
export const useSummarizeNote = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof summarizeNote>>,
    TError,
    { data: BodyType<SummarizeNoteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof summarizeNote>>,
  TError,
  { data: BodyType<SummarizeNoteBody> },
  TContext
> => {
  return useMutation(getSummarizeNoteMutationOptions(options));
};

/**
 * @summary Request a presigned URL for file upload
 */
export const getRequestUploadUrlUrl = () => {
  return `/api/storage/uploads/request-url`;
};

export const requestUploadUrl = async (
  uploadUrlRequest: UploadUrlRequest,
  options?: RequestInit,
): Promise<UploadUrlResponse> => {
  return customFetch<UploadUrlResponse>(getRequestUploadUrlUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(uploadUrlRequest),
  });
};

export const getRequestUploadUrlMutationOptions = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestUploadUrl>>,
    TError,
    { data: BodyType<UploadUrlRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestUploadUrl>>,
  TError,
  { data: BodyType<UploadUrlRequest> },
  TContext
> => {
  const mutationKey = ["requestUploadUrl"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestUploadUrl>>,
    { data: BodyType<UploadUrlRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return requestUploadUrl(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestUploadUrlMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestUploadUrl>>
>;
export type RequestUploadUrlMutationBody = BodyType<UploadUrlRequest>;
export type RequestUploadUrlMutationError = ErrorType<ErrorEnvelope>;

/**
 * @summary Request a presigned URL for file upload
 */
export const useRequestUploadUrl = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestUploadUrl>>,
    TError,
    { data: BodyType<UploadUrlRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof requestUploadUrl>>,
  TError,
  { data: BodyType<UploadUrlRequest> },
  TContext
> => {
  return useMutation(getRequestUploadUrlMutationOptions(options));
};

/**
 * @summary Serve a public asset
 */
export const getGetPublicObjectUrl = (filePath: string) => {
  return `/api/storage/public-objects/${filePath}`;
};

export const getPublicObject = async (
  filePath: string,
  options?: RequestInit,
): Promise<Blob> => {
  return customFetch<Blob>(getGetPublicObjectUrl(filePath), {
    ...options,
    method: "GET",
  });
};

export const getGetPublicObjectQueryKey = (filePath: string) => {
  return [`/api/storage/public-objects/${filePath}`] as const;
};

export const getGetPublicObjectQueryOptions = <
  TData = Awaited<ReturnType<typeof getPublicObject>>,
  TError = ErrorType<unknown>,
>(
  filePath: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPublicObject>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPublicObjectQueryKey(filePath);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicObject>>> = ({
    signal,
  }) => getPublicObject(filePath, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!filePath,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPublicObject>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPublicObjectQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPublicObject>>
>;
export type GetPublicObjectQueryError = ErrorType<unknown>;

/**
 * @summary Serve a public asset
 */

export function useGetPublicObject<
  TData = Awaited<ReturnType<typeof getPublicObject>>,
  TError = ErrorType<unknown>,
>(
  filePath: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPublicObject>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPublicObjectQueryOptions(filePath, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Serve an object entity
 */
export const getGetStorageObjectUrl = (objectPath: string) => {
  return `/api/storage/objects/${objectPath}`;
};

export const getStorageObject = async (
  objectPath: string,
  options?: RequestInit,
): Promise<Blob> => {
  return customFetch<Blob>(getGetStorageObjectUrl(objectPath), {
    ...options,
    method: "GET",
  });
};

export const getGetStorageObjectQueryKey = (objectPath: string) => {
  return [`/api/storage/objects/${objectPath}`] as const;
};

export const getGetStorageObjectQueryOptions = <
  TData = Awaited<ReturnType<typeof getStorageObject>>,
  TError = ErrorType<ErrorEnvelope>,
>(
  objectPath: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStorageObject>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStorageObjectQueryKey(objectPath);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStorageObject>>
  > = ({ signal }) =>
    getStorageObject(objectPath, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!objectPath,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStorageObject>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStorageObjectQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStorageObject>>
>;
export type GetStorageObjectQueryError = ErrorType<ErrorEnvelope>;

/**
 * @summary Serve an object entity
 */

export function useGetStorageObject<
  TData = Awaited<ReturnType<typeof getStorageObject>>,
  TError = ErrorType<ErrorEnvelope>,
>(
  objectPath: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStorageObject>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStorageObjectQueryOptions(objectPath, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
