/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * StudyCore API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Note {
  id: string;
  title: string;
  content: string;
  subject?: string;
  tags?: string[];
  imageUrl?: string;
  diagramUrl?: string;
  bulletPoints?: string[];
  createdAt: string;
  updatedAt: string;
}

export interface CreateNoteBody {
  title: string;
  content: string;
  subject?: string;
  tags?: string[];
  imageUrl?: string;
  diagramUrl?: string;
}

export interface UpdateNoteBody {
  title?: string;
  content?: string;
  subject?: string;
  tags?: string[];
  imageUrl?: string;
  diagramUrl?: string;
  bulletPoints?: string[];
}

export interface Flashcard {
  id: string;
  deckId: string;
  front: string;
  back: string;
  hint?: string;
}

export interface FlashcardDeck {
  id: string;
  title: string;
  description?: string;
  cardCount: number;
  subject?: string;
  createdAt: string;
}

export interface FlashcardDeckDetail {
  id: string;
  title: string;
  description?: string;
  subject?: string;
  cards: Flashcard[];
  createdAt: string;
}

export interface CreateFlashcardDeckBody {
  title: string;
  description?: string;
  subject?: string;
}

export interface CreateFlashcardBody {
  front: string;
  back: string;
  hint?: string;
}

export interface GlossaryTerm {
  id: string;
  term: string;
  definition: string;
  examples?: string[];
  relatedTerms?: string[];
  subject?: string;
}

export interface CreateGlossaryTermBody {
  term: string;
  definition: string;
  examples?: string[];
  relatedTerms?: string[];
  subject?: string;
}

export interface BranchNode {
  id: string;
  label: string;
  children?: BranchNode[];
}

export interface BranchTree {
  id: string;
  title: string;
  noteId?: string;
  root: BranchNode;
  createdAt: string;
}

export interface CreateBranchTreeBody {
  title: string;
  noteId?: string;
  root: BranchNode;
}

export interface StudySet {
  id: string;
  title: string;
  description?: string;
  subject?: string;
  termCount?: number;
  createdAt: string;
}

export interface CreateStudySetBody {
  title: string;
  description?: string;
  subject?: string;
}

export type SearchResultItemType =
  (typeof SearchResultItemType)[keyof typeof SearchResultItemType];

export const SearchResultItemType = {
  note: "note",
  flashcard_deck: "flashcard_deck",
  glossary_term: "glossary_term",
  study_set: "study_set",
} as const;

export interface SearchResultItem {
  id: string;
  type: SearchResultItemType;
  title: string;
  snippet: string;
  subject?: string;
}

export interface SearchResults {
  query: string;
  results: SearchResultItem[];
  total: number;
}

export type OverviewStatsTopSubjectsItem = {
  subject: string;
  count: number;
};

export interface OverviewStats {
  noteCount: number;
  flashcardDeckCount: number;
  glossaryTermCount: number;
  studySetCount: number;
  branchTreeCount: number;
  recentNotes?: Note[];
  topSubjects?: OverviewStatsTopSubjectsItem[];
}

export type ActivityItemType =
  (typeof ActivityItemType)[keyof typeof ActivityItemType];

export const ActivityItemType = {
  note: "note",
  flashcard_deck: "flashcard_deck",
  glossary_term: "glossary_term",
  study_set: "study_set",
  branch_tree: "branch_tree",
} as const;

export type ActivityItemAction =
  (typeof ActivityItemAction)[keyof typeof ActivityItemAction];

export const ActivityItemAction = {
  created: "created",
  updated: "updated",
  deleted: "deleted",
} as const;

export interface ActivityItem {
  id: string;
  type: ActivityItemType;
  title: string;
  action: ActivityItemAction;
  timestamp: string;
}

export interface GenerateFlashcardsBody {
  content: string;
  title?: string;
  count?: number;
}

export interface GenerateBranchTreeBody {
  content: string;
  title?: string;
  noteId?: string;
}

export interface DefineTermBody {
  term: string;
  context?: string;
}

export interface SummarizeNoteBody {
  content: string;
  noteId?: string;
}

export interface SummaryResult {
  bullets: string[];
  noteId?: string;
}

export interface UploadUrlRequest {
  name: string;
  /** @minimum 1 */
  size: number;
  contentType: string;
}

export interface UploadUrlResponse {
  uploadURL: string;
  objectPath: string;
  metadata?: UploadUrlRequest;
}

export interface ErrorEnvelope {
  error: string;
}

export type ListNotesParams = {
  subjectId?: string;
  search?: string;
};

export type ListFlashcardDecksParams = {
  search?: string;
};

export type ListGlossaryTermsParams = {
  search?: string;
};

export type ListSetsParams = {
  search?: string;
};

export type GlobalSearchParams = {
  q: string;
  type?: GlobalSearchType;
};

export type GlobalSearchType =
  (typeof GlobalSearchType)[keyof typeof GlobalSearchType];

export const GlobalSearchType = {
  notes: "notes",
  flashcards: "flashcards",
  glossary: "glossary",
  sets: "sets",
  all: "all",
} as const;
